---
title: "An치lisis de los empleados baltimores"
author: "Julia Can칩s"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Funcion que borra todas las variables 
rm(list = ls())
```

#Importamos datos con Rbase

```{r}
rutaFichero <- "data/Baltimore_City_Employee_Salaries.csv"
datosRbase <- read.csv(file = rutaFichero)

```

#Importamos datos con Readr 

```{r}
library(readr)
datosReadr <- read_csv("data/Baltimore_City_Employee_Salaries.csv", 
    col_types = cols(hireDate = col_date(format = "%Y-%m-%d")))
View(datosReadr)

```

#Importamos datos con rio 

```{r}
library(rio)
datosRio <- import(file = "data/Baltimore_City_Employee_Salaries.csv" )
#Hay una funci칩n llamada import(list), que dandole una lista de ficheros los importa todos a la vez

```
#Importamos fichero liena a linea: 

```{r}
fichero <- "data/Baltimore_City_Employee_Salaries.csv"
guess_encoding(fichero)
```
#Leemoa con la codificaci칩n adecuada: 
```{r}
f <- file(fichero, encoding = "UTF-8")
datosLineas <- readLines(con = f)

```


```{r}
guess_encoding('empleados.rmd')
```

